### ISSUE TITLE
Cotracker in furytools for nuke?

### ISSUE THREAD

**Issue by luuude** [magnoborgo/furytools#1]
Hi, this looks very interesting! Is it possible to use the vectors from cotracker in this or do they need to be converted somehow?

**Comment by magnoborgo** [comment]
As long you generate an image with the motion vectors data ("forward" style) it will work with any system.

Cotracker generates per point data, not per pixel data, so it would be better if the code was adapted to sample directly from the inference. Unless they open the license for commercial use I don't plan to do that.
